import React from 'react'

import './Spinner.css'

function Spinner() {
    return (
        <div className='spinner'>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
            <i>
                <b></b>
            </i>
        </div>
    )
}

export default Spinner
